import React from "react";
import SidebarLayout from "../components/SidebarLayout/SidebarLayout";
import Table from "../components/Table/Table";

type Props = {};

function Vendedores({}: Props) {
  const mockEmployees = [
    {
      cpf_funcionario: "2277663689",
      nome_funcionario: "Michal",
      salario_fixo: 25.29,
      data_admissao: "4/21/2022",
      eh_gerente: false,
      comissao_venda: 16,
      login_usuario: "mpinney0",
    },
    {
      cpf_funcionario: "8158269044",
      nome_funcionario: "Carolann",
      salario_fixo: 98.46,
      data_admissao: "2/12/2022",
      eh_gerente: false,
      comissao_venda: 33,
      login_usuario: "cnormanvill1",
    },
    {
      cpf_funcionario: "2091112755",
      nome_funcionario: "Mitzi",
      salario_fixo: 71.21,
      data_admissao: "10/14/2021",
      eh_gerente: false,
      comissao_venda: 25,
      login_usuario: "mgopsall2",
    },
    {
      cpf_funcionario: "4572336326",
      nome_funcionario: "Josee",
      salario_fixo: 8.51,
      data_admissao: "10/4/2021",
      eh_gerente: false,
      comissao_venda: 53,
      login_usuario: "jtacon3",
    },
    {
      cpf_funcionario: "1675224080",
      nome_funcionario: "Dela",
      salario_fixo: 3.84,
      data_admissao: "1/9/2022",
      eh_gerente: false,
      comissao_venda: 37,
      login_usuario: "dreuven4",
    },
    {
      cpf_funcionario: "2617777383",
      nome_funcionario: "Rhonda",
      salario_fixo: 93.74,
      data_admissao: "5/24/2022",
      eh_gerente: false,
      comissao_venda: 92,
      login_usuario: "rdragon5",
    },
    {
      cpf_funcionario: "3467615058",
      nome_funcionario: "Deeanne",
      salario_fixo: 93.38,
      data_admissao: "10/21/2021",
      eh_gerente: true,
      comissao_venda: 49,
      login_usuario: "dbewicke6",
    },
    {
      cpf_funcionario: "2802196863",
      nome_funcionario: "Celka",
      salario_fixo: 88.28,
      data_admissao: "12/28/2021",
      eh_gerente: false,
      comissao_venda: 35,
      login_usuario: "cbarhims7",
    },
    {
      cpf_funcionario: "2346060569",
      nome_funcionario: "Krista",
      salario_fixo: 64.96,
      data_admissao: "5/13/2022",
      eh_gerente: true,
      comissao_venda: 43,
      login_usuario: "kklimpt8",
    },
    {
      cpf_funcionario: "7468330115",
      nome_funcionario: "Sharlene",
      salario_fixo: 62.7,
      data_admissao: "3/25/2022",
      eh_gerente: false,
      comissao_venda: 85,
      login_usuario: "sgounod9",
    },
    {
      cpf_funcionario: "5867024776",
      nome_funcionario: "Shellysheldon",
      salario_fixo: 84.94,
      data_admissao: "1/18/2022",
      eh_gerente: true,
      comissao_venda: 52,
      login_usuario: "sroscampa",
    },
    {
      cpf_funcionario: "4501856432",
      nome_funcionario: "Gilda",
      salario_fixo: 61.28,
      data_admissao: "7/17/2022",
      eh_gerente: false,
      comissao_venda: 63,
      login_usuario: "gwarbeyb",
    },
    {
      cpf_funcionario: "5272250737",
      nome_funcionario: "Evyn",
      salario_fixo: 84.79,
      data_admissao: "1/28/2022",
      eh_gerente: false,
      comissao_venda: 83,
      login_usuario: "emccurtainc",
    },
    {
      cpf_funcionario: "5064723334",
      nome_funcionario: "Penelopa",
      salario_fixo: 19.0,
      data_admissao: "4/2/2022",
      eh_gerente: true,
      comissao_venda: 65,
      login_usuario: "pmcilveend",
    },
    {
      cpf_funcionario: "4966491002",
      nome_funcionario: "Ode",
      salario_fixo: 25.95,
      data_admissao: "6/9/2022",
      eh_gerente: true,
      comissao_venda: 97,
      login_usuario: "oherreroe",
    },
    {
      cpf_funcionario: "1948944294",
      nome_funcionario: "Tabbitha",
      salario_fixo: 5.53,
      data_admissao: "5/5/2022",
      eh_gerente: true,
      comissao_venda: 23,
      login_usuario: "twalbridgef",
    },
    {
      cpf_funcionario: "9204763051",
      nome_funcionario: "Anna-diane",
      salario_fixo: 42.91,
      data_admissao: "3/7/2022",
      eh_gerente: false,
      comissao_venda: 26,
      login_usuario: "afarryg",
    },
    {
      cpf_funcionario: "7590817201",
      nome_funcionario: "Ody",
      salario_fixo: 83.27,
      data_admissao: "10/23/2021",
      eh_gerente: true,
      comissao_venda: 56,
      login_usuario: "olockleyh",
    },
    {
      cpf_funcionario: "4254807201",
      nome_funcionario: "Jessey",
      salario_fixo: 94.46,
      data_admissao: "7/1/2022",
      eh_gerente: true,
      comissao_venda: 17,
      login_usuario: "jharnesi",
    },
    {
      cpf_funcionario: "4445990337",
      nome_funcionario: "Jocko",
      salario_fixo: 34.63,
      data_admissao: "7/16/2022",
      eh_gerente: false,
      comissao_venda: 21,
      login_usuario: "jdevoielsj",
    },
    {
      cpf_funcionario: "2498276289",
      nome_funcionario: "Violetta",
      salario_fixo: 60.95,
      data_admissao: "3/15/2022",
      eh_gerente: true,
      comissao_venda: 52,
      login_usuario: "vdeperok",
    },
    {
      cpf_funcionario: "0599648392",
      nome_funcionario: "Griffy",
      salario_fixo: 23.04,
      data_admissao: "6/10/2022",
      eh_gerente: false,
      comissao_venda: 43,
      login_usuario: "gbeel",
    },
    {
      cpf_funcionario: "2845773005",
      nome_funcionario: "Sollie",
      salario_fixo: 76.29,
      data_admissao: "8/16/2021",
      eh_gerente: true,
      comissao_venda: 42,
      login_usuario: "smandifieldm",
    },
    {
      cpf_funcionario: "3513174438",
      nome_funcionario: "Marianne",
      salario_fixo: 86.55,
      data_admissao: "8/10/2021",
      eh_gerente: true,
      comissao_venda: 35,
      login_usuario: "mvinnickn",
    },
    {
      cpf_funcionario: "8780521061",
      nome_funcionario: "Rois",
      salario_fixo: 26.5,
      data_admissao: "8/22/2021",
      eh_gerente: true,
      comissao_venda: 79,
      login_usuario: "rdorneyo",
    },
    {
      cpf_funcionario: "9473599005",
      nome_funcionario: "Cody",
      salario_fixo: 89.93,
      data_admissao: "1/1/2022",
      eh_gerente: true,
      comissao_venda: 39,
      login_usuario: "cbighamp",
    },
    {
      cpf_funcionario: "8785661244",
      nome_funcionario: "Francoise",
      salario_fixo: 28.49,
      data_admissao: "9/18/2021",
      eh_gerente: true,
      comissao_venda: 8,
      login_usuario: "fquelchq",
    },
    {
      cpf_funcionario: "7871411144",
      nome_funcionario: "Eran",
      salario_fixo: 42.49,
      data_admissao: "2/13/2022",
      eh_gerente: false,
      comissao_venda: 100,
      login_usuario: "etoxellr",
    },
    {
      cpf_funcionario: "1366864859",
      nome_funcionario: "Tadeo",
      salario_fixo: 11.22,
      data_admissao: "6/21/2022",
      eh_gerente: true,
      comissao_venda: 36,
      login_usuario: "tnervals",
    },
    {
      cpf_funcionario: "5518664281",
      nome_funcionario: "Gasparo",
      salario_fixo: 46.21,
      data_admissao: "6/14/2022",
      eh_gerente: true,
      comissao_venda: 55,
      login_usuario: "gmealandt",
    },
    {
      cpf_funcionario: "7791069377",
      nome_funcionario: "Granthem",
      salario_fixo: 59.41,
      data_admissao: "10/9/2021",
      eh_gerente: true,
      comissao_venda: 72,
      login_usuario: "gmuddleu",
    },
    {
      cpf_funcionario: "9513370070",
      nome_funcionario: "Zelma",
      salario_fixo: 68.38,
      data_admissao: "4/13/2022",
      eh_gerente: false,
      comissao_venda: 75,
      login_usuario: "zgringleyv",
    },
    {
      cpf_funcionario: "9828837498",
      nome_funcionario: "Hazlett",
      salario_fixo: 23.62,
      data_admissao: "12/17/2021",
      eh_gerente: false,
      comissao_venda: 58,
      login_usuario: "hbackw",
    },
    {
      cpf_funcionario: "5311877928",
      nome_funcionario: "Ellswerth",
      salario_fixo: 90.92,
      data_admissao: "12/3/2021",
      eh_gerente: false,
      comissao_venda: 2,
      login_usuario: "ericcax",
    },
    {
      cpf_funcionario: "9374757923",
      nome_funcionario: "Emera",
      salario_fixo: 57.48,
      data_admissao: "10/28/2021",
      eh_gerente: true,
      comissao_venda: 4,
      login_usuario: "emulvyy",
    },
    {
      cpf_funcionario: "0346740827",
      nome_funcionario: "Morena",
      salario_fixo: 71.71,
      data_admissao: "9/29/2021",
      eh_gerente: true,
      comissao_venda: 84,
      login_usuario: "malbertz",
    },
    {
      cpf_funcionario: "0012958786",
      nome_funcionario: "Jimmie",
      salario_fixo: 60.89,
      data_admissao: "9/29/2021",
      eh_gerente: true,
      comissao_venda: 84,
      login_usuario: "jdunleavy10",
    },
    {
      cpf_funcionario: "3032620422",
      nome_funcionario: "Holden",
      salario_fixo: 72.81,
      data_admissao: "4/5/2022",
      eh_gerente: false,
      comissao_venda: 70,
      login_usuario: "hdew11",
    },
    {
      cpf_funcionario: "1777125669",
      nome_funcionario: "Dynah",
      salario_fixo: 63.3,
      data_admissao: "2/15/2022",
      eh_gerente: true,
      comissao_venda: 91,
      login_usuario: "dpennoni12",
    },
    {
      cpf_funcionario: "1647862906",
      nome_funcionario: "Caesar",
      salario_fixo: 26.68,
      data_admissao: "9/14/2021",
      eh_gerente: false,
      comissao_venda: 48,
      login_usuario: "czannuto13",
    },
    {
      cpf_funcionario: "7438760936",
      nome_funcionario: "Cal",
      salario_fixo: 92.03,
      data_admissao: "6/24/2022",
      eh_gerente: true,
      comissao_venda: 74,
      login_usuario: "cilbert14",
    },
    {
      cpf_funcionario: "3373448530",
      nome_funcionario: "Augie",
      salario_fixo: 82.05,
      data_admissao: "7/18/2022",
      eh_gerente: false,
      comissao_venda: 49,
      login_usuario: "agauge15",
    },
    {
      cpf_funcionario: "8150294368",
      nome_funcionario: "Weider",
      salario_fixo: 86.29,
      data_admissao: "6/30/2022",
      eh_gerente: false,
      comissao_venda: 96,
      login_usuario: "wfarquar16",
    },
    {
      cpf_funcionario: "5396292318",
      nome_funcionario: "Aileen",
      salario_fixo: 2.02,
      data_admissao: "2/14/2022",
      eh_gerente: false,
      comissao_venda: 97,
      login_usuario: "amooring17",
    },
    {
      cpf_funcionario: "0681684720",
      nome_funcionario: "Chiarra",
      salario_fixo: 97.18,
      data_admissao: "2/23/2022",
      eh_gerente: true,
      comissao_venda: 20,
      login_usuario: "cblasoni18",
    },
    {
      cpf_funcionario: "9339564669",
      nome_funcionario: "Baird",
      salario_fixo: 65.49,
      data_admissao: "7/25/2021",
      eh_gerente: true,
      comissao_venda: 30,
      login_usuario: "bpetschel19",
    },
    {
      cpf_funcionario: "0355252090",
      nome_funcionario: "Casey",
      salario_fixo: 11.6,
      data_admissao: "3/3/2022",
      eh_gerente: false,
      comissao_venda: 44,
      login_usuario: "cgrigsby1a",
    },
    {
      cpf_funcionario: "5497253393",
      nome_funcionario: "Sollie",
      salario_fixo: 47.52,
      data_admissao: "5/24/2022",
      eh_gerente: false,
      comissao_venda: 23,
      login_usuario: "scoskerry1b",
    },
    {
      cpf_funcionario: "1911713027",
      nome_funcionario: "Bronnie",
      salario_fixo: 42.64,
      data_admissao: "10/20/2021",
      eh_gerente: false,
      comissao_venda: 35,
      login_usuario: "bambrogelli1c",
    },
    {
      cpf_funcionario: "6745675501",
      nome_funcionario: "Jordana",
      salario_fixo: 72.19,
      data_admissao: "2/5/2022",
      eh_gerente: false,
      comissao_venda: 29,
      login_usuario: "jhardie1d",
    },
  ];
  return (
    <SidebarLayout title="Vendedores Ativos">
      <Table
        columnTitles={[
          "CPF",
          "Nome",
          "Salario Fixo",
          "Data de Admissao",
          "Cargo",
          "Comissão",
          "Usuario",
        ]}
        items={mockEmployees.map((item) => {
          return {
            ...item,
            eh_gerente: item.eh_gerente ? "Gerente" : "Funcionario",
          };
        })}
        title="Lista de Vendedores Ativos"
      ></Table>
    </SidebarLayout>
  );
}

export default Vendedores;
